<?php 
require_once '../../includes/db.php';
require_once '../../includes/auth.php';
require_once '../../includes/attendance_math.php';

$id = isset($_GET['id']) ? intval($_GET['id']) : 0;

$stmt = $pdo->prepare("
    SELECT p.*, e.first_name, e.last_name, e.employee_code, e.department, e.designation, e.hire_date
    FROM payroll_records p
    JOIN employees e ON p.employee_id = e.id
    WHERE p.id = ?
");
$stmt->execute([$id]);
$payroll = $stmt->fetch();

if (!$payroll) {
    die("Payslip not found.");
}

if ($currentUser['role'] === 'employee' && intval($payroll['employee_id']) !== intval($currentUser['employee_id'] ?? 0)) {
    die("Unauthorized access.");
}

if (!in_array($currentUser['role'], ['admin', 'HR', 'employee'])) {
    die("Unauthorized access.");
}

$settingsStmt = $pdo->query("SELECT setting_key, setting_value FROM system_settings WHERE setting_key IN ('currency', 'company_name')");
$settings = [];
foreach ($settingsStmt->fetchAll() as $setting) {
    $settings[$setting['setting_key']] = $setting['setting_value'];
}

$currency = $settings['currency'] ?? 'LKR';
$companyName = $settings['company_name'] ?? 'HRM365 Enterprise';
$total_overtime_hours = floatval($payroll['overtime_hours'] ?? 0);
$unpaid_days = floatval($payroll['unpaid_days'] ?? 0);
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Payslip - <?php echo htmlspecialchars($payroll['first_name'] . ' ' . $payroll['last_name']); ?></title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <style>
        body { font-family: 'Inter', sans-serif; background: #f3f4f6; padding: 2rem; color: #1f2937; }
        .payslip-container { max-width: 800px; margin: 0 auto; background: white; padding: 3rem; border-radius: 8px; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1); }
        .header { display: flex; justify-content: space-between; border-bottom: 2px solid #e5e7eb; padding-bottom: 1.5rem; margin-bottom: 2rem; }
        .company-name { font-size: 1.5rem; font-weight: 700; color: #111827; }
        .payslip-title { font-size: 1.25rem; font-weight: 600; color: #4b5563; text-align: right; }
        .emp-details { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; margin-bottom: 2rem; background: #f9fafb; padding: 1.5rem; border-radius: 6px; }
        .detail-row { display: flex; justify-content: space-between; margin-bottom: 0.5rem; }
        .label { font-weight: 500; color: #6b7280; }
        .value { font-weight: 600; }
        
        .salary-table { width: 100%; border-collapse: collapse; margin-bottom: 2rem; }
        .salary-table th, .salary-table td { padding: 1rem; border-bottom: 1px solid #e5e7eb; text-align: left; }
        .salary-table th { background: #f9fafb; font-weight: 600; color: #4b5563; }
        .salary-table td.amount { text-align: right; font-family: monospace; font-size: 1.1rem; }
        
        .net-pay { display: flex; justify-content: space-between; background: #111827; color: white; padding: 1.5rem; border-radius: 6px; font-size: 1.25rem; font-weight: 700; }
        .print-btn { display: block; margin: 2rem auto 0; padding: 0.75rem 2rem; background: #3b82f6; color: white; border: none; border-radius: 4px; font-weight: 600; cursor: pointer; text-align: center; width: max-content; text-decoration: none; }
        
        @media print {
            body { background: white; padding: 0; }
            .payslip-container { box-shadow: none; padding: 0; }
            .print-btn { display: none; }
        }
    </style>
</head>
<body>

    <div class="payslip-container">
        <div class="header">
            <div>
                <div class="company-name"><?php echo htmlspecialchars($companyName); ?></div>
                <div style="color: #6b7280; font-size: 0.9rem; margin-top: 0.25rem;">Payroll generated by HRM365</div>
            </div>
            <div>
                <div class="payslip-title">SALARY SLIP</div>
                <div style="color: #6b7280; font-size: 0.9rem; margin-top: 0.25rem; text-align: right;">Month: <strong><?php echo date('F Y', strtotime($payroll['payroll_month'] . '-01')); ?></strong></div>
            </div>
        </div>

        <div class="emp-details">
            <div>
                <div class="detail-row"><span class="label">Employee Name:</span> <span class="value"><?php echo htmlspecialchars($payroll['first_name'] . ' ' . $payroll['last_name']); ?></span></div>
                <div class="detail-row"><span class="label">Employee ID:</span> <span class="value"><?php echo htmlspecialchars($payroll['employee_code']); ?></span></div>
                <div class="detail-row"><span class="label">Date of Joining:</span> <span class="value"><?php echo date('M d, Y', strtotime($payroll['hire_date'])); ?></span></div>
            </div>
            <div>
                <div class="detail-row"><span class="label">Department:</span> <span class="value"><?php echo htmlspecialchars($payroll['department']); ?></span></div>
                <div class="detail-row"><span class="label">Designation:</span> <span class="value"><?php echo htmlspecialchars($payroll['designation']); ?></span></div>
                <div class="detail-row"><span class="label">Status:</span> <span class="value" style="color: #10b981;"><?php echo $payroll['status']; ?></span></div>
            </div>
        </div>

        <table class="salary-table">
            <thead>
                <tr>
                    <th style="width: 60%;">Earnings</th>
                    <th style="width: 40%; text-align: right;">Amount</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Basic Salary</td>
                    <td class="amount"><?php echo htmlspecialchars($currency); ?> <?php echo number_format($payroll['base_salary'], 2); ?></td>
                </tr>
                <tr>
                    <td>Overtime Allowance <span style="font-size: 0.8rem; color: #6b7280; margin-left: 0.5rem;">(<?php echo htmlspecialchars(format_hours_minutes($total_overtime_hours)); ?>)</span></td>
                    <td class="amount" style="color: #10b981;">+<?php echo htmlspecialchars($currency); ?> <?php echo number_format($payroll['overtime_amount'], 2); ?></td>
                </tr>
                <tr>
                    <td style="font-weight: 600;">Total Earnings</td>
                    <td class="amount" style="font-weight: 600;"><?php echo htmlspecialchars($currency); ?> <?php echo number_format($payroll['base_salary'] + $payroll['overtime_amount'], 2); ?></td>
                </tr>
            </tbody>
        </table>

        <table class="salary-table" style="margin-top: -1rem;">
            <thead>
                <tr>
                    <th style="width: 60%;">Deductions</th>
                    <th style="width: 40%; text-align: right;">Amount</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Unpaid Leave / Absence Deductions <span style="font-size: 0.8rem; color: #6b7280; margin-left: 0.5rem;">(<?php echo number_format($unpaid_days, 2); ?> day(s))</span></td>
                    <td class="amount" style="color: #ef4444;">-<?php echo htmlspecialchars($currency); ?> <?php echo number_format($payroll['deductions'], 2); ?></td>
                </tr>
                <tr>
                    <td style="font-weight: 600;">Total Deductions</td>
                    <td class="amount" style="font-weight: 600;"><?php echo htmlspecialchars($currency); ?> <?php echo number_format($payroll['deductions'], 2); ?></td>
                </tr>
            </tbody>
        </table>

        <div class="net-pay">
            <div>NET SALARY PAYABLE</div>
            <div><?php echo htmlspecialchars($currency); ?> <?php echo number_format($payroll['net_salary'], 2); ?></div>
        </div>

        <div style="margin-top: 3rem; text-align: center; color: #9ca3af; font-size: 0.85rem;">
            This is a computer-generated document. No signature is required.
        </div>
    </div>

    <button onclick="window.print()" class="print-btn">Print / Save as PDF</button>

</body>
</html>
